import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import HeaderMobile from "../components/HeaderMobile";
import styles from "../styles/Home.module.css";
import illustrationWorking from "../resources/images/illustration-working.svg";
import CallToAction from "../components/CallToAction";
import ShortenALink from "../components/ShortenALink";
import AdvancedStatistics from "../components/AdvancedStatistics";
import Cards from "../components/Cards";
import LastCallToAction from "../components/LastCallToAction";
import Footer from "../components/Footer";
import HeaderDesktop from "../components/HeaderDesktop";
import ShortenLinks from "../components/ShortenLinks";

export default function Home() {
  const [mobileNav, setMobileNav] = useState(false);
  const [isDesktop, setIsDesktop] = useState(false);

  useEffect(() => {
    setIsDesktop(window.matchMedia("(min-width: 1300px)").matches);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.pageContainer}>
        {isDesktop ? (
          <HeaderDesktop />
        ) : (
          <HeaderMobile
            switchNav={() => setMobileNav((prev) => !prev)}
            nav={mobileNav}
          />
        )}
        <div className={styles.workerImage}>
          <Image
            layout="fixed"
            width={540}
            height={380}
            src={illustrationWorking}
          />
        </div>
        <CallToAction />
        <section className={styles.shortenALinkSection}>
          <ShortenALink />
        </section>
        <section className={styles.shortenALinkSection2}>
          <ShortenLinks />
          <ShortenLinks />
          <ShortenLinks />
        </section>
        <AdvancedStatistics />
        <Cards />
        <LastCallToAction />
        <Footer />
      </main>
    </div>
  );
}
