import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import illustrationWorking from "../resources/images/illustration-working.svg";
import CallToAction from "../components/CallToAction";
import { useState } from "react";
import ShortenALink from "../components/ShortenALink";
import AdvancedStatistics from "../components/AdvancedStatistics";
import Cards from "../components/Cards";
import LastCallToAction from "../components/LastCallToAction";
import Footer from "../components/Footer";

export default function Home() {
  const [mobileNav, setMobileNav] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.pageContainer}>
        <Header
          switchNav={() => setMobileNav((prev) => !prev)}
          nav={mobileNav}
        />
        <div className={styles.workerImage}>
          <Image
            layout="fixed"
            width={540}
            height={380}
            src={illustrationWorking}
          />
        </div>
        <CallToAction />
        <section className={styles.shortenALinkSection}>
          <ShortenALink />
        </section>
        <AdvancedStatistics />
        <Cards />
        <LastCallToAction />
        <Footer />
      </main>
    </div>
  );
}
